### ISSUE TITLE
[Suggestion] [Removal] Require presence of declare(strict_types = 1) in the same line as php open tag

### ISSUE THREAD

**Issue by admarc** [easir/coding-standard#4]
Morten suggested that this shouldn't be a strict rule. If we remove it then it is up to developer if he include it or not.

https://github.com/easir/coding-standard/blob/master/src/Easir/ruleset.xml#L42

**Comment by admarc** [comment]
I think I have to reconsider my vote. We don't have 100% test coverage. If we implement strict_types on code that isn't tested but use casting then we will have problem on production. So I would love to have it - but it seems to be too dangerous to have it as a rule.

**Comment by Multiply** [comment]
@admarc exactly one of the main reasons I voted no to requiring it.

**Comment by brzuchal** [comment]
@Multiply good we have a space to discuss and agree to the arguments.

**Comment by brzuchal** [comment]
Sorry wrong button! :D

**Comment by admarc** [comment]
@Multiply @brzuchal I think it is important to share doubts like this. Especially when there is a risk for our project.

**Comment by Multiply** [comment]
I already voiced some of my concerns in other channels (specifically Slack) since this project was started, so didn't feel like repeating myself again. :)
