### ISSUE TITLE
[Discuss] Omit phpDoc for parameters/returns with native types, unless adding description

### ISSUE THREAD

**Issue by gayanhewa** [easir/coding-standard#5]
I would like to confirm, does this mean we are only omitting phpDoc for Params/Return types if they are native types and not user-defined types (ie. Classes)? 

```
 public function stupidFunction(AnotherClasss $anotherClass, string $name) : NewClass
```

I think it should be for everything. 

ping @easir/backend

**Comment by mortenhauberg** [comment]
That is how I understand it, yes

**Comment by admarc** [comment]
Agree. The goal is to remove all comments that doesn't make sense (so all types). In reality @throws annotation will be used the most.
