### ISSUE TITLE
[Suggestion] We should allow Exception sufix for Exceptions

### ISSUE THREAD

**Issue by admarc** [easir/coding-standard#7]
Probably all of our exceptions are sufixed right now. cbf cannot fix it automatically. I don't think that this is that critical so my proposition is to allow Exception sufix for now (we will have less work when fixing the code).

**Comment by brzuchal** [comment]
You can still ignore one rule inside default configuration file like `phpcs.xml.dist` to adjust ruleset to project needs! Otherwise, we create another ruleset which is tightly coupled with Zebra only project.

**Comment by brzuchal** [comment]
IMO we shouldn't do that way, cause ignoring is better than removal. If we remove we all agree to add `Exception` suffix in all projects, even if we don't agree it's the right way. We wanted Doctrine standards and removing the rule won't make us get into transformation phase that way.
We can still put in Zebra projects an `<exclude ...>` tag for one rule if we agree we're not ready for this and we wanna go that path but not yet ready.
If we remove the rule then for Zebra it's a peaceful state, but for other projects may not be.
AFAIR we wanna acheive common Easi'r projects ruleset standard. Not another for Zebra only, right?
I mayt be wrong and if I am please correct me.

**Comment by admarc** [comment]
Maybe we should consider it as a global thing for : Interface, Abstract and Exception as a sufix or prefix. If we will go for it (to remove sufixes and/or prefixes) then it wont be only removing them from names. Let's consider Symfony ParseException as an example. `throw new Parse` is not pretty. We would have to pick the right name for each exception/interface/class (maybe `throw new ParseFailure` for given example).

**Comment by admarc** [comment]
Pull request: https://github.com/easir/coding-standard/pull/10
