### ISSUE TITLE
[Suggestion] Remove rule that force us to import php functions

### ISSUE THREAD

**Issue by admarc** [easir/coding-standard#8]
Right now cbf automatically add every native function which was used in the file:
```
use function end;
use function implode;
use function preg_match;
use function reset;
use function sprintf;
```
I'm not sure if we want that. Do we have any clear benefits to have it?

**Comment by mortenhauberg** [comment]
The benefit is a _minor_ performance improvement, but I'm not sure it worth it.,

**Comment by gayanhewa** [comment]
It does improve overall readability, but its bit of an overkill to have separate lines, I would opt for a single line import if that is supported. 

```
use function some\namespace\{fn_a, fn_b, fn_c};
```

**Comment by admarc** [comment]
@gayanhewa I'm not sure if the fixer is able to do it by itself. To do it manually it would be hell. If this voting will fail then we can discuss / check options.

**Comment by brzuchal** [comment]
@gayanhewa group use statements are a mistake they shouldn't exist in PHP even that's what the contributor says. Imagine diff with one removal from group use statement!

**Comment by brzuchal** [comment]
If there is an option to adjust the rule to do not import global function names which already are prefixed with `\` then I agree, it should require importing namespaced function names IMO.

**Comment by admarc** [comment]
@brzuchal There is an option: 
`allowFallbackGlobalFunctions`: allows using global functions via fallback name without `use` (i.e. `phpversion()`).

**Comment by brzuchal** [comment]
@admarc ok then treat my vote as Yes if including that option.

**Comment by admarc** [comment]
https://github.com/easir/coding-standard/pull/9

**Comment by brzuchal** [comment]
#9

**Comment by brzuchal** [comment]
#9
